__version__ = '0.3.3'
__lib_name__ = 'ffmpeg_for_python'
__autor__ = 'PauloCesar-dev404'
__repo__ = 'https://github.com/PauloCesar-dev404/ffmpeg-for-python'
__lib__ = f'https://raw.githubusercontent.com/PauloCesar-dev404/ffmpeg-for-python/main/{__lib_name__}-{__version__}-py3-none-any.whl'
__source__ = f'https://raw.githubusercontent.com/PauloCesar-dev404/ffmpeg-for-python/main/{__lib_name__}-{__version__}.tar.gz'